#!/usr/bin/env bash
# Update a server
sudo apt-get update -y -qq

# Install haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

# Configure HAProxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo chmod -R u+rwx /etc/haproxy/
sudo cat << EOF > /etc/haproxy/haproxy.cfg
defaults
        mode    http
        timeout connect 10s
        timeout client  15s
        timeout server  15s
	timeout http-request 10s
        

frontend http-in
    bind *:80
    default_backend servers

backend servers
   balance roundrobin
   server 381033-web-01 35.174.207.21:80 check
   server 381033-web-02 54.197.64.186:80 check
EOF

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start HAProxy service
sudo service haproxy start
