#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code and count the occurrences

awk '{ print $1,$3,$9 }' apache-access.log | sort | uniq -c | sort -rn | awk '{ print $2,$3,$1 }'
